[workspace]
members = ["shelby_client", "shelby_node", "shelby_protobuf"]
resolver = "3"

[profile.optimized]
inherits = "release"
codegen-units = 1
lto = "thin"
panic = "abort"

[profile.test-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
